# Generated by Django 4.2.2 on 2023-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0005_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
