# Generated by Django 4.2.2 on 2023-07-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0008_alter_registrationform_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='buyer',
            name='message',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
