# Generated by Django 4.2.2 on 2023-07-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0009_delete_test_buyer_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='message',
            new_name='buyer_message',
        ),
    ]
