# Generated by Django 4.2.2 on 2023-07-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0006_alter_product_image'),
        ('demosite', '0010_rename_message_buyer_buyer_message'),
    ]

    operations = [
    ]
