# Generated by Django 4.2.2 on 2023-07-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0011_merge_20230707_0033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrationform',
            unique_together={('email',)},
        ),
    ]
