# Generated by Django 4.2.2 on 2023-07-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0012_alter_registrationform_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
